### ISSUE TITLE
[Problem]: AK47, M4A1 trajectory optimization

### ISSUE THREAD

**Issue by Herooyyy** [DeniedAccessLife/ArduinoStrike#4]
Can AK47 or M4A1 repair fire to 1 point? it too scattered

**Comment by DeniedAccessLife** [comment]
Sorry, could you write more clearly and in detail, it's just that at the moment, my English is too bad and I don't understand what you mean.

**Comment by NevaYue** [comment]
I mean, can you optimize the trajectory? After I turned on the Arduino Strike, the ballistics of AK47 and m4a1 were too scattered.

**Comment by DeniedAccessLife** [comment]
I wanted to clarify, is there still a recoil problem with the AK47 and M4A1?

If so, how much of the spread is improperly controlled?
This will help me better understand how to optimize the system to reduce the spread.

**Comment by Herooyyy** [comment]
Thanks for your reply. it takes so long time.I think it just game's random cause it. No problem
And i solve connection problem:Use old ArduinoIDE to update my Arduino.

**Comment by DeniedAccessLife** [comment]
Thank you for your reply! When the issue was first raised, there were limited options available to optimize the patterns, which is why there was no immediate response. However, I’ve just released a new update where some patterns have been improved. I hope this helps with the trajectory optimization. Feel free to let me know if you encounter any further issues or have additional feedback!
