### ISSUE TITLE
[Problem]: "I’m stuck on this page and not moving forward."

### ISSUE THREAD

**Issue by DevaGwava** [DeniedAccessLife/ArduinoStrike#8]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe your problem

Conntecting .... 

### Steps to reproduce

"I uploaded it to Arduino, then ran the executable, but it’s stuck on this page after completing the settings."

### Hardware details

Arduino leonado

### Additional context

![image](https://github.com/user-attachments/assets/29dbb522-c205-45cd-ab39-7c9980edbfb4)

**Comment by DeniedAccessLife** [comment]
Hi!

Could you please clarify if your Arduino Leonardo is visible in the Device Manager? This will help us better understand what might be causing the connection issue.

Thank you!

**Comment by DevaGwava** [comment]
![image](https://github.com/user-attachments/assets/a54930de-a8dc-46c2-bbc6-368b464b6b50)

After uploading, the name displayed in Device Manager changed from Arduino Leonardo (COM2) to USB Serial Device (COM8).

**Comment by DeniedAccessLife** [comment]
Thank you for your patience. I’m currently investigating the issue you’re experiencing with the connection to the Arduino Leonardo. Here's what I’m doing:

1. **Issue Investigation:**
   I understand that your program is stuck on the connection page after completing the settings. This might be related to how the device is being detected and connected.

2. **Improved Device Detection:**
   To resolve the problem, I’m working on improving the device detection process. Previously, the program searched for the Arduino by its name (e.g., “Arduino Leonardo”), but now I’m adding an additional check using **PID (Product ID) and VID (Vendor ID)**. This method is more reliable and helps the program identify the Arduino device, even if there's a discrepancy in the name.

3. **Next Steps:**
   - I’m currently testing the new detection method. It will ensure that the Arduino is recognized by its **PID/VID** instead of just the name, which should resolve the issue you’re facing.
   - A new release will be available soon, with this fix included, which should allow for a more reliable connection to the Arduino device.

Thank you for your patience while I work on this fix. I’ll update you as soon as the new version is ready for download.

**Comment by DeniedAccessLife** [comment]
Thank you for your patience. I’ve just released a new version of ArduinoStrike that includes significant improvements to the device detection process. The program now uses both the device name and PID/VID to identify your Arduino, which should resolve the issue with your board being misrecognized as a "USB Serial Device."

### Next Steps:
1. Please download the latest release from [GitHub Releases](https://github.com/DeniedAccessLife/ArduinoStrike/releases).
2. Test the new version with your Arduino Leonardo.
3. If the issue persists, try running the **Debug** version of the application. This version provides detailed logs, which will help me pinpoint any remaining problems.

### If Errors Persist:
- Locate the generated log file (`arduino_debug.log`) in the program’s folder.
- Share the contents of the log file here so I can analyze it further.

Thank you for your support and for helping to improve ArduinoStrike! I look forward to hearing your feedback. 😊

**Comment by DevaGwava** [comment]
[arduino_debug.log](https://github.com/user-attachments/files/18080579/arduino_debug.log)

**Comment by DeniedAccessLife** [comment]
Thank you for sharing the log file—it’s very helpful in diagnosing the issue. Based on the logs, I can confirm that the program is unable to detect your Arduino device due to the following reasons:

1. **Device Name Mismatch**:  
   Your Arduino is recognized in the Device Manager as **USB Serial Device (COM7)** instead of **Arduino Leonardo**. The current version of the program searches specifically for the name "Arduino Leonardo," so this discrepancy prevents proper detection.

2. **VID/PID Mismatch**:  
   The `HARDWAREID` for your device is `USB\VID_046D&PID_C084`, which does not match the VID/PID patterns defined in the program (e.g., `VID_2341&PID_8036` for Arduino Leonardo). As a result, the secondary detection method also fails.

### Suggested Fix:
1. **Uninstall and Reinstall the Driver**:  
   - Open the **Device Manager**.  
   - Locate **USB Serial Device (COM7)** under the **Ports (COM & LPT)** section.  
   - Right-click on it and select **Uninstall Device**. Make sure to check **Delete the driver software for this device** if prompted.  
   - Disconnect the Arduino board and reconnect it.  

2. **Install the Correct Driver**:  
   - Download the correct driver for your Arduino Leonardo device from the following link:  
     [Arduino Leonardo Driver](https://github.com/user-attachments/files/18083619/arduino-driver-1.6.4.zip)
   - Run the driver installation and ensure the Arduino Leonardo appears correctly in the Device Manager as **Arduino Leonardo (COMX)**.

3. **Modify Detection Parameters**:  
   If the above steps don’t resolve the issue, I can modify the program to accommodate generic names like "USB Serial Device" or add your device's VID/PID (`VID_046D&PID_C084`) to the detection logic. Let me know if you’d like to test an updated version. 

Let me know if these steps resolve the issue, or feel free to reach out with the updated log if you need further assistance! 😊

**Comment by DevaGwava** [comment]
I’ve tried following every method, but the name remains the same.

**Comment by DeniedAccessLife** [comment]
Thank you for your patience and for trying the suggested steps.  

I wanted to let you know that I’ve just released a new version of ArduinoStrike, which includes several significant updates to address device detection issues like the one you’re experiencing.  

**Release Highlights:**  
- **Improved Device Detection**: The program now uses a more reliable detection mechanism that searches for devices using VID/PID patterns, display names, or a combination of both.  
- **Enhanced Logging**: The logs are now more detailed, helping to pinpoint specific detection or connection issues.  
- **Device Selection Menu**: If no device matches the saved configuration or detection criteria, the program will now display a menu of all detected devices, allowing you to manually select the correct one.  
- **Configuration File Logic**: The program now automatically updates or removes outdated configuration files to prevent conflicts caused by device name or port changes.  

Please download the latest version from GitHub Releases and test it with your Arduino. If your device is still not automatically recognized, you’ll now have the ability to manually select it from the detected devices list.  

Let me know if this resolves the issue for you, or feel free to share the updated log file if you encounter any problems. Your feedback is always appreciated! 😊

**Comment by DevaGwava** [comment]
It's a great idea to allow users to select the connection port manually. The status is now showing as "Working," but I've encountered a new issue: the Recoil Control is not functioning. I have configured it to X1 mouse button (0x05).

**Comment by DevaGwava** [comment]
![image](https://github.com/user-attachments/assets/d3e4dd06-c03a-4338-8440-888455fe4316)
Here are my settings:
The Colorbot function works, but the Recoil function does not.
I pressed F3 (M4A1) and then the XButton1 key, which I configured in the settings, but nothing happened.
I checked the log, and there were no error messages.
The only log entry is: Message sent: MOUSE_LEFT_CLICK after I triggered the Colorbot function.

**Comment by DeniedAccessLife** [comment]
It seems the program is not functioning correctly due to an issue with the configuration settings. Let me clarify how to configure the parameters properly:  

1. **Sensitivity**  
Both sensitivity parameters (`Sensitivity`), (`Zoom Sensitivity`) must match the sensitivity values in the game. If your sensitivity in the game is set to "8", the same value should be set in the program. This ensures accurate recoil compensation.

2. **Confirmation Key**  
You set the confirmation key to **VK_RBUTTON (0x02)** — the right mouse button. This is not recommended because the right mouse button is commonly used for aiming. In this case, recoil control will only work while holding the right mouse button, which can cause problems, such as detaching a suppressor on certain weapons. It is highly recommended to use another key for confirmation.  

3. **Suggested Configuration**  
To avoid issues and ensure proper functionality, I recommend using the following configuration:  

```
0   // Bhop (disabled)
1   // Rapid Fire (enabled)
8   // Sensitivity (maximum value)
1   // Zoom Sensitivity (default value)
0   // Confirmation Key (disabled)
58  // ColorBot Activation Key (0x58 — X key)
20  // ColorBot Threshold (maximum value)
1   // Fast Reload (enabled)
Please note that there is no support for comments in the configuration file, they are indicated solely for your understanding!
```

**Steps to Fix:**  

1. Open the `Settings.cfg` file in a text editor.
2. Replace the configuration with the settings suggested above, updating important values such as sensitivity.
3. Save the file and restart the program.

If you have any further questions or encounter issues, please share your updated configuration or logs for additional assistance. 😊
